{ pkgs, rakuPackage }:

let
  packages = import ./packages.nix { inherit pkgs rakuPackage; };
in

# Overrides for individual packages in order to declare native dependencies.
# The packages.nix list is autogenerated and doesn't seem to know about native dependencies
# (even though there's code in generate-nix.pl that should theoretically deal with it).
# So this lets us patch individual packages as needed. Not just for native dependencies,
# we can also make other arbitrary changes as needed.
packages.overrideScope' (self: super: {
  rakuPackages = super.rakuPackages // {
    # Package overrides go here
  };
})
